### PR TITLE
500/503 HttpException subclasses

### PR DESCRIPTION
**Pull request by danielfinke**

### CODE REVIEW

**Comment by k-anderson** [comment]
@danielfinke which APIs return a 500 not_found?  I suspect those are bugs :)

**Comment by danielfinke** [comment]
@k-anderson it looks like the only API to behave that way was GET to phone_numbers when the number didn't exist. I compared the response from our 3.22 cluster and our 4.1 cluster. The issue must have been patched at some point. 3.22 gives a 500 not_found, 4.1 as expected returns a 404.

I guess the decision here is whether to bother supporting the 3.22 response. If not, let me know, I'll remove that part of the PR.

**Comment by swysor** [comment]
We don't care about the 3.22 compatibility so you can remove that part from this PR and I will merge this. Also note, I merged the patch change PR and made a tag 2.0.1 which includes this non-backwards compatible change.

**Comment by danielfinke** [comment]
@swysor Alright, I have removed the 3.22 compatibility code. Thanks for tackling these PRs!

**Comment by swysor** [comment]
Thanks for all the great contributions. Keep em coming!

**Pull request merged**
